// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDveJJRuiODFa5NgJbbiOJ_mAoA4gL5HOk',
    appId: '1:1055946951054:web:dc86b264d0946c6c693cdf',
    messagingSenderId: '1055946951054',
    projectId: 'chadchat-97e3e',
    authDomain: 'chadchat-97e3e.firebaseapp.com',
    storageBucket: 'chadchat-97e3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBmTtCOXanVK1iZHiiCgMTqwoNzP2G8D8',
    appId: '1:1055946951054:android:dd555b02cd8e3669693cdf',
    messagingSenderId: '1055946951054',
    projectId: 'chadchat-97e3e',
    storageBucket: 'chadchat-97e3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdeTYKcS8nlcLMAat5-AT4-kZddm2vwkM',
    appId: '1:1055946951054:ios:9091a2685f871451693cdf',
    messagingSenderId: '1055946951054',
    projectId: 'chadchat-97e3e',
    storageBucket: 'chadchat-97e3e.appspot.com',
    iosBundleId: 'com.example.chadGigaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdeTYKcS8nlcLMAat5-AT4-kZddm2vwkM',
    appId: '1:1055946951054:ios:9091a2685f871451693cdf',
    messagingSenderId: '1055946951054',
    projectId: 'chadchat-97e3e',
    storageBucket: 'chadchat-97e3e.appspot.com',
    iosBundleId: 'com.example.chadGigaChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDveJJRuiODFa5NgJbbiOJ_mAoA4gL5HOk',
    appId: '1:1055946951054:web:c5d5c94e35648002693cdf',
    messagingSenderId: '1055946951054',
    projectId: 'chadchat-97e3e',
    authDomain: 'chadchat-97e3e.firebaseapp.com',
    storageBucket: 'chadchat-97e3e.appspot.com',
  );
}
